- name: Set User Password
  user:
    name: "{{ default_username }}"
    update_password: always
    password: "{{ default_user_password | password_hash('sha512') }}"
  when: "default_user_password |length > 0"

