- name: Generate munge key
  shell: "base64 /dev/urandom |tr -dc 'a-zA-Z0-9' |head -c 32"
  register: munge_key

- name: Write local munge key file
  copy:
    content: "{{ munge_key.stdout }}"
    dest: "/etc/munge/munge.key"

- name: Turn on munge
  service: name=munge state=restarted enabled=yes

- name: Create SLURM log dirs
  file:
    path: /opt/flight/opt/slurm/var/log/slurm
    state: directory
    owner: nobody

- name: Create SLURM run directory
  file:
    path: /opt/flight/opt/slurm/var/run
    state: directory
    owner: nobody

- name: Generate SLURM conf
  template:
    src: slurm.conf
    dest: /opt/flight/opt/slurm/etc/slurm.conf

- name: Create spool directory
  file:
    path: /opt/flight/opt/slurm/var/spool/slurm.state
    state: directory
    owner: nobody
    group: nobody

- name: Turn on SLURM controller daemon
  service: name=flight-slurmctld state=restarted enabled=yes

- name: Turn on SLURM exec daemon
  service: name=flight-slurmd state=restarted enabled=yes

